envs:
  NCCL_DEBUG: INFO
  NCCL_CUMEM_HOST_ENABLE: "0"
  VLLM_NCCL_SO_PATH: "/usr/lib/x86_64-linux-gnu/libnccl.so.2.21.5"
  VLLM_TORCH_PROFILER_DIR: /root/vllm_workbench/profiler/
  RAY_CGRAPH_get_timeout: "10000"
  BENCHMARK_CONFIG_PATH: "/tmp/vllm_exp/benchmark_config.json"
  DEPLOYMENT_CONFIG_PATH: "/tmp/vllm_exp/vllm_config.json"
  KV_SYNC_USE_CPU: "0"
  VLLM_USE_CPU_MODEL: "0"
  CUDA_LAUNCH_BLOCKING: "1"
  NCCL_DEBUG: "INFO"
projects:
  - project: "migration_test_sync"
    type: "one_off_test"
    network:
      delays: [0]
      # 每个 pipeline 并行 rank 的可达 IP（请根据实际机器 IP 修改）
      rank_to_ip:
        0: "head"
        1: "worker1"
    vllm:
      pipeline_parallel_size: 2
      gpu_memory_utilization: 0.75
      start_pp_layer_partitions:
        - "8,56"
    migration:
      is_migration: true
      migration_steps: [30]
      alternative_configs:
        "0": [32, 32]
        "1": [32, 32]
    benchmark:
      profile: false
      print_outputs: true
      data_num_requests: [20, 50]
      input_output_lens: [ [512, 256], [512, 64]]
      running_num_requests: [20, 50]
      running_request_rates: [2.2, 1]
is_log_cover: true
