envs:
  NCCL_DEBUG: INFO
  NCCL_CUMEM_HOST_ENABLE: "0"
  VLLM_NCCL_SO_PATH: "/usr/lib/x86_64-linux-gnu/libnccl.so.2.21.5"
  VLLM_TORCH_PROFILER_DIR: /root/vllm_workbench/profiler/
  RAY_CGRAPH_get_timeout: "10000"
  BENCHMARK_CONFIG_PATH: "/tmp/vllm_exp/benchmark_config.json"
  DEPLOYMENT_CONFIG_PATH: "/tmp/vllm_exp/vllm_config.json"
projects:
  - project: "simple_test"
    type: "one_off_test"
    network:
      delays: [0]
      # 每个 pipeline 并行 rank 的可达 IP（示例：本机测试时均为 127.0.0.1）
      rank_to_ip:
        0: "127.0.0.1"
        1: "127.0.0.1"
    vllm:
      pipeline_parallel_size: 2
      gpu_memory_utilization: 0.9
      start_pp_layer_partitions:
        - "28,36"
    migration:
      is_migration: false
    benchmark:
      request_rates: [2.5]
      profile: false
      data_num_requests:
        - 1
      input_output_lens:
        - [512, 64]
is_log_cover: true
